# Per-wallet F1 analysis: Bravado vs the free Polymarket Data API vs racinglines

Companion to `bravado_data_eval.ipynb`. That one asked whether Bravado can rebuild our market data. This one asks the fairer question for wallet-level work: **for the biggest F1 traders, what does each source say about the same wallet?**

| Source | Cost | What it is here |
|---|---|---|
| Polymarket Data API | free, no key | what `racinglines/markets/polymarket/sync.py` already calls: the market tape, plus per-wallet trades, positions and closed positions |
| Bravado Trader Data API | 1 credit per request | per-wallet profile, categories, positions, trade log |
| racinglines DB | n/a | `market_trades` (taker fills with a `wallet`), the database `DATABASE_URL` points at (default: the local Mac Postgres, not the VM) |

Steps: (1) define the F1 universe from our `market_links` (exact `condition_id` keys); (2) find the biggest F1 wallets from the free tape of the largest F1 markets; (3) what our own DB holds for them; (4) the free per-wallet baseline; (5) the same wallets from Bravado; (6) side by side; (7) F1 PnL per token; (8) trade rows and how far back each source reaches; (9) ledger; (10) a verdict computed from the outputs.

Every request is logged, capped, and cached on disk under `data/cache/` (gitignored), so re-running spends nothing. Bravado spends about 5 credits per wallet; the knobs are in the first code cell. Clear the outputs before committing: they hold third-party wallet data.

In [1]:
import hashlib, hmac, json, os, sys, time
import urllib.error, urllib.request
from pathlib import Path
from urllib.parse import quote, urlencode

import httpx
import pandas as pd
from sqlalchemy import text

REPO = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "pyproject.toml").exists())
sys.path.insert(0, str(REPO))
from racinglines import sports
from racinglines.db.config import get_engine

# ---- knobs ----
TOP_MARKETS = 12     # F1 markets (largest by volume) whose tape is scanned to find the wallets
TAPE_PAGES = 10      # pages of 500 rows per market, newest first (free requests, cached)
TOP_N = 10           # biggest wallets analysed on Bravado (about 5 credits each)
TRADE_PAGES = 2      # Bravado trade-log pages (500 rows each) per wallet
MAX_REQUESTS = 60    # live Bravado requests per kernel session (1 credit each)
MAX_FREE = 600       # live Polymarket Data API requests per kernel session (free)
TIMEOUT_S = 60

KEY = "1208b0814bd344afbf4e30a87ba0ce8ab44c8727af0a81bbe082b00fcbc6e719"
SECRET = os.environ["BRAVADO_API_SECRET"]
BASE = "https://partner-api.bravadotrade.com"
CACHE = REPO / "data" / "cache" / "bravado"              # shared with bravado_data_eval.ipynb
FREE_CACHE = REPO / "data" / "cache" / "polymarket_data_api"
CACHE.mkdir(parents=True, exist_ok=True)
FREE_CACHE.mkdir(parents=True, exist_ok=True)


class Bravado:
    def __init__(self, key, secret, max_requests):
        self.key, self.secret, self.max_requests = key, secret, max_requests
        self.log = []

    @staticmethod
    def signed_path(path, params):
        # https://docs.bravadotrade.com/authentication: keys sorted, values URL-encoded, each key once.
        query = "&".join(quote(k, safe="-_.~") + "=" + quote(str(v), safe="-_.~") for k, v in sorted(params.items()))
        return path + ("?" + query if query else "")

    def live_used(self):
        return sum(not r["cached"] for r in self.log)

    def get(self, path, label=None, **params):
        """Return (status, body). HTTP errors and timeouts are returned (status 0 = no response), not raised."""
        rp = self.signed_path(path, params)
        cache_file = CACHE / (hashlib.sha256(rp.encode()).hexdigest()[:20] + ".json")
        if cache_file.exists():
            hit = json.loads(cache_file.read_text())
            self._record(label, rp, hit["status"], 0, 0, True, hit["rate_remaining"])
            return hit["status"], hit["body"]
        if self.live_used() >= self.max_requests:
            raise RuntimeError(f"request budget of {self.max_requests} used up; raise MAX_REQUESTS to continue")
        ts = str(int(time.time() * 1000))
        payload = "\n".join([ts, "GET", rp, hashlib.sha256(b"").hexdigest()])
        sig = hmac.new(self.secret.encode(), payload.encode(), hashlib.sha256).hexdigest()
        req = urllib.request.Request(BASE + rp, headers={
            "X-BRAVADO-API-KEY": self.key, "X-BRAVADO-TIMESTAMP": ts, "X-BRAVADO-SIGNATURE": sig})
        t0 = time.time()
        try:
            with urllib.request.urlopen(req, timeout=TIMEOUT_S) as resp:
                status, raw, headers = resp.status, resp.read(), resp.headers
        except urllib.error.HTTPError as e:
            status, raw, headers = e.code, e.read(), e.headers
        except (TimeoutError, urllib.error.URLError) as e:
            self._record(label, rp, 0, 0, round((time.time() - t0) * 1000), False, None)
            return 0, {"_error": repr(e)}
        try:
            body = json.loads(raw.decode())
        except ValueError:
            body = {"_text": raw.decode(errors="replace")[:300]}
        remaining = headers.get("X-RateLimit-Remaining")
        self._record(label, rp, status, len(raw), round((time.time() - t0) * 1000), False, remaining)
        if status in (200, 404):
            cache_file.write_text(json.dumps({"status": status, "body": body, "rate_remaining": remaining}))
        return status, body

    def _record(self, label, rp, status, nbytes, ms, cached, remaining):
        self.log.append(dict(label=label or rp.split("?")[0], path=rp, status=status, bytes=nbytes,
                             ms=ms, cached=cached, rate_remaining=remaining))


class DataAPI:
    """Polymarket Data API (public, free). Same cache-and-cap discipline as the Bravado client."""
    def __init__(self, max_requests):
        self.max_requests, self.log = max_requests, []
        self.http = httpx.Client(base_url="https://data-api.polymarket.com", timeout=30,
                                 headers={"User-Agent": "racinglines-notebook"})

    def live_used(self):
        return sum(not r["cached"] for r in self.log)

    def get(self, path, **params):
        key = path + "?" + urlencode(sorted(params.items()))
        cache_file = FREE_CACHE / (hashlib.sha256(key.encode()).hexdigest()[:20] + ".json")
        if cache_file.exists():
            self.log.append(dict(path=path, cached=True, status=200))
            return json.loads(cache_file.read_text())
        if self.live_used() >= self.max_requests:
            raise RuntimeError(f"free request budget of {self.max_requests} used up; raise MAX_FREE to continue")
        for attempt in range(4):
            time.sleep(0.15)
            r = self.http.get(path, params=params)
            if r.status_code == 429 or r.status_code >= 500:
                time.sleep(2 ** attempt)
                continue
            break
        self.log.append(dict(path=path, cached=False, status=r.status_code))
        r.raise_for_status()
        body = r.json()
        cache_file.write_text(json.dumps(body))
        return body


client = Bravado(KEY, SECRET, MAX_REQUESTS)
free = DataAPI(MAX_FREE)
engine = get_engine()


def short(w):
    return w[:6] + "…" + w[-4:]


print(f"repo:  {REPO}\ndb:    {engine.url.render_as_string(hide_password=True)}\n"
      f"cache: bravado {len(list(CACHE.glob('*.json')))} files, data-api {len(list(FREE_CACHE.glob('*.json')))} files")

repo:  /Users/lalligagger/py_dev/racinglines
db:    postgresql+psycopg://racinglines:***@localhost:5433/racinglines
cache: bravado 18 files, data-api 165 files

In [2]:
# 1. The F1 universe, from our own market_links. Exact keys only: a market is F1 if and only if its condition_id is here.
# F1 is matched on condition_id, not token_id: most of our F1 markets list only their "Yes" token, so a "No" trade
# carries a token we do not hold.
F1_CODE = sports.load("f1")["competition"]["code"]
with engine.connect() as c:
    f1_links = pd.read_sql_query(text("""
        SELECT ml.token_id, ml.condition_id, ml.question, ml.outcome, ml.event_title, ml.prediction, ml.closed, ml.volume
        FROM market_links ml JOIN competitions co ON co.id = ml.competition_id
        WHERE ml.exchange = 'polymarket' AND co.code = :code AND ml.token_id IS NOT NULL AND ml.condition_id IS NOT NULL
    """), c, params=dict(code=F1_CODE))
f1_links["volume"] = pd.to_numeric(f1_links["volume"], errors="coerce").fillna(0)
F1_CONDS = set(f1_links.condition_id)

markets = (f1_links.groupby("condition_id")
           .agg(question=("question", "first"), event_title=("event_title", "first"), prediction=("prediction", "first"),
                closed=("closed", "all"), volume=("volume", "max"))
           .reset_index().sort_values("volume", ascending=False).reset_index(drop=True))
scan = markets.head(TOP_MARKETS).reset_index(drop=True)
scan_conds = set(scan.condition_id)
CSV = ",".join(scan.condition_id)  # Data API filters wallet endpoints by a comma-separated list of condition ids
one_token = int((f1_links.groupby("condition_id").token_id.nunique() == 1).sum())

print(f"{F1_CODE}: {len(F1_CONDS)} Polymarket markets, {len(f1_links)} tokens, "
      f"{int((~markets.closed).sum())} markets still open; recorded volume ${markets.volume.sum():,.0f}")
print(f"{one_token} of {len(F1_CONDS)} markets list a single outcome token in market_links, hence matching on condition_id")
print(f"scan set: the {len(scan)} largest markets = ${scan.volume.sum():,.0f} "
      f"({scan.volume.sum() / markets.volume.sum():.0%} of F1 volume by our market_links.volume)")
display(scan.assign(condition_id=scan.condition_id.str[:12])[["condition_id", "event_title", "question", "prediction", "closed", "volume"]])

f1_wdc: 6712 Polymarket markets, 7285 tokens, 71 markets still open; recorded volume $463,001,494
6139 of 6712 markets list a single outcome token in market_links, hence matching on condition_id
scan set: the 12 largest markets = $172,020,068 (37% of F1 volume by our market_links.volume)

,condition_id,event_title,question,prediction,closed,volume
0,0x7e8953cc66,F1 Drivers Champion,Will George Russell be the 2025 Drivers Champion?,champion,True,2.969811e+07
1,0x9c60e608e4,F1 Drivers Champion,Will Lewis Hamilton be the 2025 Drivers Champion?,champion,True,2.054660e+07
2,0x8e7409627b,F1 Drivers Champion,Will Charles Leclerc be the 2025 Drivers Champ...,champion,True,1.405202e+07
3,0xa2b7d29282,F1 Drivers' Champion,Will Oliver Bearman be the 2026 F1 Drivers' Ch...,champion,True,1.289782e+07
4,0xde3d62bece,F1 Drivers' Champion,Will Franco Colapinto be the 2026 F1 Drivers' ...,champion,True,1.222975e+07
5,0x00f89ad584,F1 Drivers' Champion,Will Valtteri Bottas be the 2026 F1 Drivers' C...,champion,True,1.220247e+07
6,0x7a6491e3c9,F1 Drivers' Champion,Will Arvid Lindblad be the 2026 F1 Drivers' Ch...,champion,True,1.204943e+07
7,0x596b82d837,F1 Drivers' Champion,Will Alexander Albon be the 2026 F1 Drivers' C...,champion,True,1.187491e+07
8,0x9ca9ea6bca,F1 Drivers' Champion,Will Sergio Pérez be the 2026 F1 Drivers' Cham...,champion,True,1.179691e+07
9,0xc62b78f7a1,F1 Drivers' Champion,Will Lance Stroll be the 2026 F1 Drivers' Cham...,champion,True,1.173927e+07
10,0x88d573d2ba,F1 Drivers' Champion,Will Pierre Gasly be the 2026 F1 Drivers' Cham...,champion,True,1.151041e+07
11,0xe3afb091ba,F1 Drivers Champion,Will Max Verstappen be the 2025 Drivers Champion?,champion,True,1.142238e+07

In [3]:
# 2. Find the biggest F1 wallets: free tape of the scan markets, newest first, both sides of each fill (takerOnly=false).
# Ranking is by USDC traded (price x size) in the rows scanned, so it is "biggest in the recent tape", not all-time.
tape_rows, coverage = [], []
for i, m in enumerate(scan.itertuples(), 1):
    rows = []
    for page in range(TAPE_PAGES):
        batch = free.get("/trades", market=m.condition_id, limit=500, offset=page * 500, takerOnly="false")
        rows += batch
        if len(batch) < 500:
            break
    tape_rows += rows
    ts = [r["timestamp"] for r in rows]
    coverage.append(dict(market=m.question[:50], rows=len(rows),
                         oldest=pd.to_datetime(min(ts), unit="s", utc=True) if ts else None,
                         newest=pd.to_datetime(max(ts), unit="s", utc=True) if ts else None, market_volume=m.volume))
    print(f"progress tape: market {i} of {len(scan)} · {len(rows)} rows · free requests so far {free.live_used()}", flush=True)

tape = pd.DataFrame(tape_rows)
tape["usdc"] = tape["price"].astype(float) * tape["size"].astype(float)
wallets = (tape.groupby("proxyWallet")
           .agg(f1_usdc=("usdc", "sum"), rows=("usdc", "size"), markets=("conditionId", "nunique"),
                buy_share=("side", lambda s: (s == "BUY").mean()), name=("name", "first"), pseudonym=("pseudonym", "first"),
                first=("timestamp", "min"), last=("timestamp", "max"))
           .sort_values("f1_usdc", ascending=False))
wallets["first"] = pd.to_datetime(wallets["first"], unit="s", utc=True)
wallets["last"] = pd.to_datetime(wallets["last"], unit="s", utc=True)
TOP = wallets.index[:TOP_N].tolist()

print(f"\ntape: {len(tape):,} rows, {tape.proxyWallet.nunique():,} distinct wallets, ${tape.usdc.sum():,.0f} traded")
print(f"top {TOP_N} wallets = {wallets.f1_usdc.iloc[:TOP_N].sum() / tape.usdc.sum():.0%} of scanned USDC; "
      f"largest single wallet = {wallets.f1_usdc.iloc[0] / tape.usdc.sum():.0%}")
display(pd.DataFrame(coverage))
display(wallets.head(15).reset_index().assign(wallet=lambda d: d.proxyWallet.map(short))
        [["wallet", "name", "pseudonym", "f1_usdc", "rows", "markets", "buy_share", "first", "last"]])

progress tape: market 1 of 12 · 5000 rows · free requests so far 0
progress tape: market 2 of 12 · 5000 rows · free requests so far 0
progress tape: market 3 of 12 · 5000 rows · free requests so far 0
progress tape: market 4 of 12 · 5000 rows · free requests so far 0
progress tape: market 5 of 12 · 5000 rows · free requests so far 0
progress tape: market 6 of 12 · 5000 rows · free requests so far 0
progress tape: market 7 of 12 · 5000 rows · free requests so far 0
progress tape: market 8 of 12 · 5000 rows · free requests so far 0
progress tape: market 9 of 12 · 5000 rows · free requests so far 0
progress tape: market 10 of 12 · 5000 rows · free requests so far 0
progress tape: market 11 of 12 · 5000 rows · free requests so far 0
progress tape: market 12 of 12 · 5000 rows · free requests so far 0

tape: 60,000 rows, 9,675 distinct wallets, $6,108,968 traded
top 10 wallets = 15% of scanned USDC; largest single wallet = 3%

,market,rows,oldest,newest,market_volume
0,Will George Russell be the 2025 Drivers Champion?,5000,2025-10-28 11:32:13+00:00,2025-11-10 06:22:55+00:00,2.969811e+07
1,Will Lewis Hamilton be the 2025 Drivers Champion?,5000,2025-07-26 18:27:12+00:00,2025-09-21 15:35:14+00:00,2.054660e+07
2,Will Charles Leclerc be the 2025 Drivers Champ...,5000,2025-10-12 11:19:47+00:00,2025-10-20 02:52:09+00:00,1.405202e+07
3,Will Oliver Bearman be the 2026 F1 Drivers' Ch...,5000,2026-06-21 09:30:41+00:00,2026-09-12 19:57:04+00:00,1.289782e+07
4,Will Franco Colapinto be the 2026 F1 Drivers' ...,5000,2026-06-21 09:43:38+00:00,2026-09-12 19:57:12+00:00,1.222975e+07
5,Will Valtteri Bottas be the 2026 F1 Drivers' C...,5000,2026-06-25 06:54:59+00:00,2026-09-06 11:25:57+00:00,1.220247e+07
6,Will Arvid Lindblad be the 2026 F1 Drivers' Ch...,5000,2026-07-04 03:59:44+00:00,2026-09-12 19:57:25+00:00,1.204943e+07
7,Will Alexander Albon be the 2026 F1 Drivers' C...,5000,2026-06-25 11:39:10+00:00,2026-09-06 18:35:52+00:00,1.187491e+07
8,Will Sergio Pérez be the 2026 F1 Drivers' Cham...,5000,2026-07-01 03:21:52+00:00,2026-09-07 16:12:46+00:00,1.179691e+07
9,Will Lance Stroll be the 2026 F1 Drivers' Cham...,5000,2026-06-22 05:54:26+00:00,2026-09-04 02:15:25+00:00,1.173927e+07
10,Will Pierre Gasly be the 2026 F1 Drivers' Cham...,5000,2026-06-23 03:27:01+00:00,2026-09-12 19:57:49+00:00,1.151041e+07
11,Will Max Verstappen be the 2025 Drivers Champion?,5000,2025-12-07 13:38:35+00:00,2025-12-07 20:15:37+00:00,1.142238e+07

,wallet,name,pseudonym,f1_usdc,rows,markets,buy_share,first,last
0,0xba63…893b,heliosz,Mysterious-Quiche,191890.128800,5,1,1.000000,2025-12-07 14:45:01+00:00,2025-12-07 14:58:21+00:00
1,0x0aa3…64e9,DimasXT,Important-Toaster,190179.261378,51,1,0.588235,2025-12-07 14:30:21+00:00,2025-12-07 14:54:59+00:00
2,0x3402…9446,madril,Far-Flung-Wardrobe,129891.370250,4,1,0.500000,2025-10-28 20:46:03+00:00,2025-11-06 10:01:35+00:00
3,0x6bfb…11fd,jiokplk,Shameful-Smuggling,86224.624315,16,1,0.500000,2025-07-27 15:18:05+00:00,2025-07-27 15:46:17+00:00
4,0xa973…f0f6,0xA9736e281441255FC815A65aE4F9Ba4C0B77F0F6-175...,Abandoned-Cabbage,67932.000000,10,1,1.000000,2025-12-07 14:32:23+00:00,2025-12-07 14:33:29+00:00
5,0x69aa…8847,tsekinming01,Valid-Defense,53147.115900,34,1,0.411765,2025-12-07 13:40:39+00:00,2025-12-07 14:59:01+00:00
6,0xbd1a…fb82,,,50868.531581,10,1,0.500000,2025-07-27 05:04:17+00:00,2025-07-27 05:12:15+00:00
7,0xc5ef…f435,,,50268.672721,10,1,0.500000,2025-07-27 16:10:01+00:00,2025-07-27 16:16:17+00:00
8,0xa0c5…7235,gfdgpp,Decimal-Accomplishment,50268.193441,10,1,0.500000,2025-07-27 12:07:57+00:00,2025-07-27 12:16:19+00:00
9,0x1db6…058c,0x1DB651f2F5Ee468150b00610FaFcEc08830D058C-175...,Well-Off-Double,50268.113561,10,1,0.500000,2025-07-27 12:07:11+00:00,2025-07-27 12:15:31+00:00
10,0x4a69…85f3,,,50267.614311,10,1,0.500000,2025-07-27 13:56:51+00:00,2025-07-27 14:26:29+00:00
11,0xbc09…1d68,oklkbless,Rosy-Barrage,50267.474521,10,1,0.500000,2025-07-27 05:33:33+00:00,2025-07-27 05:41:21+00:00
12,0xcf8b…6147,iomlk,Frightened-Culture,50267.394641,10,1,0.500000,2025-07-27 16:35:23+00:00,2025-07-27 16:55:09+00:00
13,0x0e05…6240,imolkm,Liquid-Portion,50267.314761,10,1,0.500000,2025-07-27 16:34:09+00:00,2025-07-27 16:42:31+00:00
14,0x2dd2…eb4c,,,50267.314761,10,1,0.500000,2025-07-27 05:33:53+00:00,2025-07-27 05:44:57+00:00

In [4]:
# 3. What racinglines itself can say per wallet: F1 rows in market_trades (taker fills only, `wallet` = proxyWallet).
F1_CONDS_SQL = """SELECT ml.condition_id FROM market_links ml JOIN competitions co ON co.id = ml.competition_id
                  WHERE ml.exchange = 'polymarket' AND co.code = :code AND ml.condition_id IS NOT NULL"""
with engine.connect() as c:
    our_cov = pd.read_sql_query(text(f"""
        SELECT count(*) AS f1_trades, count(t.wallet) AS with_wallet, count(DISTINCT t.wallet) AS distinct_wallets,
               min(t.ts) AS first_ts, max(t.ts) AS last_ts
        FROM market_trades t WHERE t.condition_id IN ({F1_CONDS_SQL})"""), c, params=dict(code=F1_CODE))
    our_by_wallet = pd.read_sql_query(text(f"""
        SELECT lower(t.wallet) AS wallet, count(*) AS our_rows, min(t.ts) AS our_first, max(t.ts) AS our_last
        FROM market_trades t
        WHERE lower(t.wallet) = ANY(:w) AND t.condition_id IN ({F1_CONDS_SQL}) GROUP BY 1"""), c,
        params=dict(code=F1_CODE, w=[w.lower() for w in TOP]))

row = our_cov.iloc[0]
print(f"our Polymarket F1 market_trades: {int(row.f1_trades):,} rows, {int(row.with_wallet):,} with a wallet "
      f"({row.with_wallet / max(row.f1_trades, 1):.1%}), {int(row.distinct_wallets):,} distinct wallets, {row.first_ts} to {row.last_ts}")
print(f"top {TOP_N} wallets with any F1 row in our DB: {len(our_by_wallet)}")
display(our_by_wallet)

our Polymarket F1 market_trades: 0 rows, 0 with a wallet (0.0%), 0 distinct wallets, None to None
top 10 wallets with any F1 row in our DB: 0

Empty DataFrame
Columns: [wallet, our_rows, our_first, our_last]
Index: []

In [5]:
# 4. The free per-wallet baseline, scoped to the scan markets (server-side filter `market=<condition ids>`).
def free_pages(path, page, max_pages, **params):
    out = []
    for p in range(max_pages):
        batch = free.get(path, limit=page, offset=p * page, **params)
        out += batch
        if len(batch) < page:
            break
    return out


free_w = {}
for i, w in enumerate(TOP, 1):
    free_w[w] = dict(
        trades=free_pages("/trades", 500, 4, user=w, market=CSV, takerOnly="false"),
        positions=free_pages("/positions", 500, 2, user=w, market=CSV, sizeThreshold=0),
        closed=free_pages("/closed-positions", 50, 10, user=w, market=CSV))
    d = free_w[w]
    print(f"progress free: wallet {i} of {len(TOP)} {short(w)} · {len(d['trades'])} trades, "
          f"{len(d['positions'])} open, {len(d['closed'])} closed · free requests so far {free.live_used()}", flush=True)

f_trades = pd.DataFrame([dict(wallet=w, token_id=r["asset"], ts_s=int(r["timestamp"]), side_n=r["side"], size=float(r["size"]),
                              price=float(r["price"]), tx=str(r["transactionHash"]).lower().removeprefix("0x"))
                         for w in TOP for r in free_w[w]["trades"]],
                        columns=["wallet", "token_id", "ts_s", "side_n", "size", "price", "tx"])
f_trades["usdc"] = f_trades["size"] * f_trades["price"]

# PnL per token on the free side: open positions (cashPnl + realizedPnl) plus closed positions (realizedPnl).
f_pnl = (pd.DataFrame([dict(wallet=w, token_id=r["asset"], condition_id=r["conditionId"], outcome=r.get("outcome"),
                            pnl=float(r["cashPnl"]) + float(r["realizedPnl"])) for w in TOP for r in free_w[w]["positions"]] +
                      [dict(wallet=w, token_id=r["asset"], condition_id=r["conditionId"], outcome=r.get("outcome"),
                            pnl=float(r["realizedPnl"])) for w in TOP for r in free_w[w]["closed"]],
                      columns=["wallet", "token_id", "condition_id", "outcome", "pnl"])
         .groupby(["wallet", "token_id"], as_index=False)
         .agg(condition_id=("condition_id", "first"), outcome=("outcome", "first"), pnl=("pnl", "sum")))

print(f"\nfree side: {len(f_trades):,} trade rows, {len(f_pnl):,} (wallet, token) PnL rows over {f_trades.wallet.nunique()} wallets")

progress free: wallet 1 of 10 0xba63…893b · 5 trades, 0 open, 1 closed · free requests so far 0
progress free: wallet 2 of 10 0x0aa3…64e9 · 51 trades, 0 open, 1 closed · free requests so far 0
progress free: wallet 3 of 10 0x3402…9446 · 6 trades, 0 open, 2 closed · free requests so far 0
progress free: wallet 4 of 10 0x6bfb…11fd · 16 trades, 0 open, 1 closed · free requests so far 0
progress free: wallet 5 of 10 0xa973…f0f6 · 10 trades, 0 open, 1 closed · free requests so far 0
progress free: wallet 6 of 10 0x69aa…8847 · 123 trades, 0 open, 1 closed · free requests so far 0
progress free: wallet 7 of 10 0xbd1a…fb82 · 10 trades, 0 open, 1 closed · free requests so far 0
progress free: wallet 8 of 10 0xc5ef…f435 · 10 trades, 0 open, 1 closed · free requests so far 0
progress free: wallet 9 of 10 0xa0c5…7235 · 10 trades, 0 open, 1 closed · free requests so far 0
progress free: wallet 10 of 10 0x1db6…058c · 10 trades, 0 open, 1 closed · free requests so far 0

free side: 251 trade rows, 11 (wallet, token) PnL rows over 10 wallets

In [ ]:
# 5. Bravado, one wallet at a time, biggest first: profile, categories, positions (open + closed), trade log.
# About 5 credits per wallet. Neither the trade log nor the position list can be filtered by market, so F1 rows are picked
# out afterwards. Bravado's `market_id` is Polymarket's numeric market id (e.g. 525361), not the condition id, so rows are
# keyed by `token_id` and mapped to `condition_id` through TOKEN_COND (exact lookups: our market_links plus every
# asset -> conditionId pair the free API returned for the scan markets).
# The docs name `cursor_ts` and a log-index cursor but the response also carries a tx/token cursor, so page 2 tries
# the candidate parameter styles in order and keeps the first one that returns a clean, older page.
CURSOR_STYLES = [
    {"cursor_ts": "next_cursor", "cursor_log_idx": "next_cursor_log_idx", "cursor_tx": "next_cursor_tx", "cursor_token": "next_cursor_token"},
    {"cursor_ts": "next_cursor", "next_cursor_log_idx": "next_cursor_log_idx", "next_cursor_tx": "next_cursor_tx", "next_cursor_token": "next_cursor_token"},
]
cursor_style = None

TOKEN_COND = dict(zip(f1_links.token_id, f1_links.condition_id))
TOKEN_COND.update(zip(tape.asset, tape.conditionId))
for _w in TOP:
    for _r in free_w[_w]["trades"] + free_w[_w]["positions"] + free_w[_w]["closed"]:
        TOKEN_COND[_r["asset"]] = _r["conditionId"]


def trade_pages(w):
    """Up to TRADE_PAGES pages of 500 TRADE rows. Returns (rows, pages fetched, whether older pages exist)."""
    global cursor_style
    path = f"/trader-analytics/traders/{w}/trades"
    st, b = client.get(path, label="trades p1", type="TRADE", limit=500)
    rows = list(b.get("trades", [])) if st == 200 else []
    pages = 1
    more = st == 200 and len(rows) == 500 and b.get("next_cursor") is not None
    while more and pages < TRADE_PAGES:
        seen = {json.dumps(r, sort_keys=True) for r in rows}
        found = None
        for style in ([cursor_style] if cursor_style else CURSOR_STYLES):
            params = {k: b[v] for k, v in style.items() if v in b}
            st2, b2 = client.get(path, label=f"trades p{pages + 1} style {CURSOR_STYLES.index(style)}", type="TRADE", limit=500, **params)
            new = b2.get("trades", []) if st2 == 200 else []
            if new and not any(json.dumps(r, sort_keys=True) in seen for r in new):
                cursor_style, found = style, (b2, new)
                break
        if found is None:
            print(f"  {short(w)}: no cursor style gave a clean page {pages + 1}; stopping at {pages}")
            break
        b, new = found
        rows += new
        pages += 1
        more = len(new) == 500 and b.get("next_cursor") is not None
    return rows, pages, more


def position_pages(w):
    """Up to 3 pages of 1000 positions (open and closed). Returns (rows, total reported by the API)."""
    rows, total = [], None
    for page in range(3):
        st, b = client.get(f"/trader-analytics/traders/{w}/positions", label="positions", limit=1000, offset=page * 1000)
        if st != 200:
            break
        rows += b.get("positions", [])
        total = b.get("total", len(rows))
        if (page + 1) * 1000 >= total:
            break
    return rows, total


bv = {}
for i, w in enumerate(TOP, 1):
    try:
        st_p, profile = client.get(f"/trader-analytics/traders/{w}", label="profile", window="all")
        st_c, cats = client.get(f"/trader-analytics/traders/{w}/categories", label="categories")
        positions, pos_total = position_pages(w)
        trades, pages, more = trade_pages(w)
    except RuntimeError as e:
        print(f"stopped before wallet {i} of {len(TOP)}: {e}")
        break
    bv[w] = dict(profile=profile if st_p == 200 else {}, status=(st_p, st_c),
                 categories=cats.get("categories", []) if st_c == 200 and isinstance(cats, dict) else [],
                 positions=positions, pos_total=pos_total, trades=trades, trade_pages=pages, trade_more=more)
    print(f"progress bravado: wallet {i} of {len(TOP)} {short(w)} · {len(positions)} of {pos_total} positions, "
          f"{len(trades)} trade rows in {pages} page(s) · live requests {client.live_used()} of {MAX_REQUESTS}", flush=True)

W = [w for w in TOP if w in bv]


def num(s):
    return pd.to_numeric(s, errors="coerce")


b_pos = pd.DataFrame([dict(r, wallet=w) for w in W for r in bv[w]["positions"]])
for col in ["token_id", "market_id", "outcome", "realized_pnl", "unrealized_pnl"]:
    if col not in b_pos:
        b_pos[col] = None
b_pos["pnl"] = num(b_pos.realized_pnl).fillna(0) + num(b_pos.unrealized_pnl).fillna(0)
b_pos["condition_id"] = b_pos.token_id.map(TOKEN_COND)
b_pos["f1"] = b_pos.condition_id.isin(F1_CONDS)
b_pos["scan"] = b_pos.condition_id.isin(scan_conds)

rows_bt = []
for w in W:
    seen = set()
    for r in bv[w]["trades"]:
        k = json.dumps(r, sort_keys=True)
        if k not in seen:
            seen.add(k)
            rows_bt.append(dict(r, wallet=w))
b_trades = pd.DataFrame(rows_bt)
for col in ["ts", "block_timestamp", "shares", "usdc_amount", "price_cents", "tx_hash", "side", "token_id", "market_id"]:
    if col not in b_trades:
        b_trades[col] = None
b_trades["ts_s"] = num(b_trades.ts).fillna(num(b_trades.block_timestamp))  # seconds since epoch
b_trades["size"] = num(b_trades.shares)
b_trades["usdc"] = num(b_trades.usdc_amount)
b_trades["price"] = num(b_trades.price_cents) / 100
b_trades["tx"] = b_trades.tx_hash.astype("string").str.lower().str.replace(r"^0x", "", regex=True)  # Bravado has no 0x prefix
b_trades["side_n"] = b_trades.side.map({"B": "BUY", "S": "SELL", "BUY": "BUY", "SELL": "SELL"})
b_trades["condition_id"] = b_trades.token_id.map(TOKEN_COND)
b_trades["f1"] = b_trades.condition_id.isin(F1_CONDS)
b_trades["scan"] = b_trades.condition_id.isin(scan_conds)
b_trades["size2"] = b_trades["size"].round(2)
f_trades["size2"] = f_trades["size"].round(2)

print(f"\nBravado side: {len(W)} wallets, {len(b_pos):,} positions ({int(b_pos.f1.sum())} F1), "
      f"{len(b_trades):,} trade rows ({int(b_trades.f1.sum())} F1); live requests {client.live_used()} of {MAX_REQUESTS}; "
      f"cursor style that worked: {CURSOR_STYLES.index(cursor_style) if cursor_style else 'not needed or none'}")
print(f"TOKEN_COND maps {len(TOKEN_COND):,} tokens; Bravado F1 rows can only be found for tokens in it "
      f"(Yes tokens of every F1 market, both tokens of the scan markets)")

In [7]:
# 6. One row per wallet: who they are and how big, per source.
def num1(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return float("nan")


rows = []
for w in W:
    p, pos = bv[w]["profile"], b_pos[b_pos.wallet == w]
    cats = pd.DataFrame(bv[w]["categories"])
    top_cat, top_share = None, float("nan")
    if len(cats) and "volume_usdc" in cats:
        cats["v"] = num(cats.volume_usdc)
        best = cats.sort_values("v", ascending=False).iloc[0]
        top_cat, top_share = best.get("category"), best.v / cats.v.sum()
    our = our_by_wallet[our_by_wallet.wallet == w.lower()]
    rows.append(dict(
        wallet=short(w), name=p.get("username") or wallets.pseudonym.get(w),
        tape_f1_usdc=wallets.f1_usdc[w],
        bv_volume=num1(p.get("volume")), bv_pnl=num1(p.get("overall_pnl")), bv_fees=num1(p.get("total_fees")),
        bv_trades=p.get("total_trades"), bv_win_rate=num1(p.get("win_rate")), bv_markets=p.get("unique_markets"),
        first_seen=pd.to_datetime(p["first_seen_ts"], unit="s", utc=True).date() if p.get("first_seen_ts") else None,
        top_category=top_cat, top_category_share=top_share,
        positions=len(pos), positions_total=bv[w]["pos_total"], f1_positions=int(pos.f1.sum()),
        f1_pnl_all_f1_markets=pos.loc[pos.f1, "pnl"].sum(), scan_pnl_bravado=pos.loc[pos.scan, "pnl"].sum(),
        scan_pnl_free=f_pnl.loc[f_pnl.wallet == w, "pnl"].sum(), our_f1_rows=int(our.our_rows.iloc[0]) if len(our) else 0))
summary = pd.DataFrame(rows)
display(summary[["wallet", "name", "tape_f1_usdc", "bv_volume", "bv_pnl", "bv_fees", "bv_trades", "bv_win_rate", "bv_markets",
                 "first_seen", "top_category", "top_category_share"]])
display(summary[["wallet", "positions", "positions_total", "f1_positions", "f1_pnl_all_f1_markets",
                 "scan_pnl_bravado", "scan_pnl_free", "our_f1_rows"]])

,wallet,name,tape_f1_usdc,bv_volume,bv_pnl,bv_fees,bv_trades,bv_win_rate,bv_markets,first_seen,top_category,top_category_share
0,0xba63…893b,heliosz,191890.128800,5.468658e+05,-15009.788736,130.17753,307,0.3500,22,2025-12-05,Sports,0.975770
1,0x0aa3…64e9,DimasXT,190179.261378,1.049598e+07,-269415.371099,22.29338,17802,0.8472,1282,2024-07-22,Sports,0.861137
2,0x3402…9446,madril,129891.370250,2.435379e+07,94622.783689,4009.22582,6986,0.2709,505,2024-11-16,Sports,0.501944
3,0x6bfb…11fd,jiokplk,86224.624315,8.622662e+04,-43.910118,0.00000,19,0.6667,3,2025-07-27,Sports,0.999977
4,0xa973…f0f6,0xA9736e281441255FC815A65aE4F9Ba4C0B77F0F6-175...,67932.000000,1.475029e+06,-127709.534549,0.00000,3187,0.6800,153,2025-09-14,Geopolitics,0.553013
5,0x69aa…8847,tsekinming01,53147.115900,5.526433e+07,-121573.403742,2104.81616,23195,0.7829,1095,2021-01-07,Crypto,0.294239
6,0xbd1a…fb82,,50868.531581,5.087153e+04,-25.453313,0.00000,15,0.7500,4,2025-07-27,Sports,0.999961
7,0xc5ef…f435,,50268.672721,5.026967e+04,-25.162999,0.00000,11,0.5000,2,2025-07-27,Sports,0.999980
8,0xa0c5…7235,gfdgpp,50268.193441,5.027968e+04,-25.128653,0.00000,13,0.6667,3,2025-07-27,Sports,0.999771
9,0x1db6…058c,0x1DB651f2F5Ee468150b00610FaFcEc08830D058C-175...,50268.113561,5.026911e+04,-25.163736,0.00000,11,0.5000,2,2025-07-27,Sports,0.999980

,wallet,positions,positions_total,f1_positions,f1_pnl_all_f1_markets,scan_pnl_bravado,scan_pnl_free,our_f1_rows
0,0xba63…893b,22,22,0,0.0,0.0,203.0423,0
1,0x0aa3…64e9,1280,1280,0,0.0,0.0,0.0000,0
2,0x3402…9446,511,511,0,0.0,0.0,-76.9197,0
3,0x6bfb…11fd,3,3,0,0.0,0.0,-43.9462,0
4,0xa973…f0f6,161,161,0,0.0,0.0,68.0000,0
5,0x69aa…8847,1152,1152,0,0.0,0.0,-2009.3592,0
6,0xbd1a…fb82,4,4,0,0.0,0.0,-25.4724,0
7,0xc5ef…f435,2,2,0,0.0,0.0,-25.1720,0
8,0xa0c5…7235,3,3,0,0.0,0.0,-25.1718,0
9,0x1db6…058c,2,2,0,0.0,0.0,-25.1718,0

In [ ]:
# 7. Do the sources agree on a wallet's F1 PnL? Per (wallet, token), scan markets only, same scope on both sides.
# Bravado: realized + unrealized per position row. Free: open (cashPnl + realizedPnl) + closed (realizedPnl).
bp = (b_pos[b_pos.scan].groupby(["wallet", "token_id"], as_index=False)
      .agg(bravado=("pnl", "sum"), b_cond=("condition_id", "first"), b_outcome=("outcome", "first")))
fp = f_pnl.rename(columns={"pnl": "free"})
pnl_cmp = bp.merge(fp, on=["wallet", "token_id"], how="outer", indicator=True)
pnl_cmp = pnl_cmp[pnl_cmp.wallet.isin(W)].copy()
pnl_cmp["condition_id"] = pnl_cmp.condition_id.fillna(pnl_cmp.b_cond)
pnl_cmp["outcome"] = pnl_cmp.outcome.fillna(pnl_cmp.b_outcome)
pnl_cmp["diff"] = pnl_cmp.bravado.fillna(0) - pnl_cmp.free.fillna(0)
pnl_cmp["abs_diff"] = pnl_cmp["diff"].abs()
pnl_cmp["both"] = pnl_cmp["_merge"] == "both"
pnl_cmp["bravado_only"] = pnl_cmp["_merge"] == "left_only"
pnl_cmp["free_only"] = pnl_cmp["_merge"] == "right_only"
pnl_cmp["off_by_1usd"] = pnl_cmp.abs_diff > 1

by_wallet = (pnl_cmp.groupby("wallet")
             .agg(tokens=("token_id", "size"), in_both=("both", "sum"), bravado_only=("bravado_only", "sum"),
                  free_only=("free_only", "sum"), bravado_total=("bravado", "sum"), free_total=("free", "sum"),
                  max_abs_diff=("abs_diff", "max"), tokens_off_by_1usd=("off_by_1usd", "sum"))
             .reset_index())
by_wallet["total_diff"] = by_wallet.bravado_total - by_wallet.free_total
by_wallet["wallet"] = by_wallet.wallet.map(short)
display(by_wallet)

q = markets.set_index("condition_id").question
worst = pnl_cmp.sort_values("abs_diff", ascending=False).head(10).copy()
worst["wallet"] = worst.wallet.map(short)
worst["market"] = [f"{str(q.get(c, '?'))[:45]} [{o}]" for c, o in zip(worst.condition_id, worst.outcome)]
display(worst[["wallet", "market", "bravado", "free", "diff", "_merge"]])

In [9]:
# 8. Do the trade rows agree, and how far back does each source reach? Scan markets only.
# Bravado returns the wallet's newest rows across every market, so its pages reach back only as far as `reach`; the free
# API filters by market on the server and pages back further. A free row is only "expected" in Bravado if it is inside `reach`.
KEY_B = ["token_id", "ts_s", "side_n", "size2"]  # ~31-46% of Bravado TRADE rows have no tx_hash, so the tx join is a second, partial check
rows = []
for w in W:
    bt, ft = b_trades[b_trades.wallet == w], f_trades[f_trades.wallet == w]
    bts = bt[bt.scan]
    reach = bt.ts_s.min() if len(bt) else float("nan")
    fin = ft[ft.ts_s >= reach] if len(bt) else ft.iloc[0:0]
    m_key = bts.drop_duplicates(KEY_B).merge(fin.drop_duplicates(KEY_B), on=KEY_B, suffixes=("_bv", "_free"))
    m_tx = bts[bts.tx.notna()].drop_duplicates(["tx", "token_id"]).merge(
        fin.drop_duplicates(["tx", "token_id"]), on=["tx", "token_id"], suffixes=("_bv", "_free"))
    rows.append(dict(
        wallet=short(w), bv_rows=len(bt), bv_reach=pd.to_datetime(reach, unit="s", utc=True) if len(bt) else None,
        bv_older_pages_exist=bv[w]["trade_more"], bv_f1_rows=int(bt.f1.sum()), bv_scan_rows=len(bts),
        free_rows=len(ft), free_in_reach=len(fin), free_older_than_reach=len(ft) - len(fin),
        matched=len(m_key), matched_by_tx=len(m_tx), bv_unmatched=len(bts.drop_duplicates(KEY_B)) - len(m_key),
        free_unmatched=len(fin.drop_duplicates(KEY_B)) - len(m_key), bv_tx_null=bt.tx.isna().mean() if len(bt) else float("nan"),
        max_price_diff=(m_key.price_bv - m_key.price_free).abs().max() if len(m_key) else float("nan")))
trade_cmp = pd.DataFrame(rows)
display(trade_cmp)

,wallet,bv_rows,bv_reach,bv_older_pages_exist,bv_f1_rows,bv_scan_rows,free_rows,free_in_reach,free_older_than_reach,matched,matched_by_tx,bv_unmatched,free_unmatched,bv_tx_null,max_price_diff
0,0xba63…893b,326,2025-12-05 01:59:47+00:00,False,0,0,5,5,0,0,0,0,5,0.058282,NaN
1,0x0aa3…64e9,1000,2026-01-31 05:44:10+00:00,True,0,0,51,0,51,0,0,0,0,0.096000,NaN
2,0x3402…9446,1000,2026-05-24 20:37:21+00:00,True,0,0,6,0,6,0,0,0,0,0.079000,NaN
3,0x6bfb…11fd,22,2025-07-27 15:18:05+00:00,False,0,0,16,16,0,0,0,0,16,0.136364,NaN
4,0xa973…f0f6,1000,2025-12-11 00:26:20+00:00,True,0,0,10,0,10,0,0,0,0,0.024000,NaN
5,0x69aa…8847,1000,2026-07-24 02:55:19+00:00,True,0,0,123,0,123,0,0,0,0,0.049000,NaN
6,0xbd1a…fb82,19,2025-07-27 05:04:17+00:00,False,0,0,10,10,0,0,0,0,10,0.210526,NaN
7,0xc5ef…f435,13,2025-07-27 16:10:01+00:00,False,0,0,10,10,0,0,0,0,10,0.153846,NaN
8,0xa0c5…7235,16,2025-07-27 12:07:57+00:00,False,0,0,10,10,0,0,0,0,10,0.187500,NaN
9,0x1db6…058c,13,2025-07-27 12:07:11+00:00,False,0,0,10,10,0,0,0,0,10,0.153846,NaN

In [10]:
# 9. Ledger: what this run cost.
log = pd.DataFrame(client.log)
if len(log):
    led = (log.assign(live=~log.cached, label=log.label.str.replace(r" style \d+$", "", regex=True))
           .groupby("label").agg(requests=("path", "size"), live=("live", "sum"), cached=("cached", "sum"),
                                 not_200=("status", lambda s: int((s != 200).sum())), kb=("bytes", lambda s: round(s.sum() / 1024, 1))))
    display(led)
    print(f"Bravado: {int(led.live.sum())} live requests = {int(led.live.sum())} credits (cap {MAX_REQUESTS}); "
          f"{int(led.cached.sum())} served from the disk cache; last X-RateLimit-Remaining: "
          f"{log.rate_remaining.dropna().iloc[-1] if log.rate_remaining.notna().any() else 'n/a'}")
flog = pd.DataFrame(free.log)
if len(flog):
    print(f"Polymarket Data API: {int((~flog.cached).sum())} live requests, {int(flog.cached.sum())} cached (cap {MAX_FREE}); free")

            requests  live  cached  not_200      kb
label
categories        10    10       0        0     9.6
positions         12    12       0        0  1240.7
profile           10    10       0        0     7.6
trades p1         10    10       0        0   995.4
trades p2          4     4       0        0   849.6

Bravado: 46 live requests = 46 credits (cap 60); 0 served from the disk cache; last X-RateLimit-Remaining: 299
Polymarket Data API: 0 live requests, 150 cached (cap 600); free

In [11]:
# 10. Measured verdict: every line is computed from the outputs above.
n = len(W)
print(f"Sample: the {n} largest F1 wallets by USDC in the recent tape of the {len(scan)} largest F1 markets "
      f"({scan.volume.sum() / markets.volume.sum():.0%} of F1 volume); the tape reaches back to "
      f"{pd.DataFrame(coverage).oldest.max():%Y-%m-%d} at the shallowest market.")
print(f"\nOur DB: {int(our_cov.with_wallet.iloc[0]):,} of {int(our_cov.f1_trades.iloc[0]):,} F1 trades carry a wallet "
      f"({our_cov.with_wallet.iloc[0] / max(our_cov.f1_trades.iloc[0], 1):.1%}); {len(our_by_wallet)} of the top {len(TOP)} wallets appear at all.")

if len(pnl_cmp):
    both = pnl_cmp[pnl_cmp.both]
    print(f"\nF1 PnL per token: {len(pnl_cmp)} (wallet, token) pairs; {len(both)} on both sides, "
          f"{int(pnl_cmp.bravado_only.sum())} Bravado only, {int(pnl_cmp.free_only.sum())} free only.")
    print(f"  of the {len(both)} on both sides, {int((both.abs_diff <= 1).sum())} agree within $1; "
          f"max |diff| ${both.abs_diff.max():,.2f}; wallets whose totals agree within $1: "
          f"{int((by_wallet.total_diff.abs() <= 1).sum())} of {len(by_wallet)}")
if len(trade_cmp):
    inreach = trade_cmp.free_in_reach.sum()
    print(f"\nTrade rows (scan markets): free API holds {trade_cmp.free_rows.sum():,}; "
          f"{inreach:,} of them are inside Bravado's page reach, and {trade_cmp.matched.sum():,} of those match a Bravado row "
          f"on (token, second, side, size); {trade_cmp.free_older_than_reach.sum():,} are older than Bravado's pages reach.")
    print(f"  Bravado pages cover {trade_cmp.bv_rows.sum():,} rows over {trade_cmp.bv_rows.gt(0).sum()} wallets; "
          f"older pages exist for {int(trade_cmp.bv_older_pages_exist.sum())} of them; "
          f"tx_hash is null on {b_trades.tx.isna().mean():.0%} of rows; "
          f"max price diff on matches {trade_cmp.max_price_diff.max():.4f}")
    print(f"  F1 rows Bravado returned in total: {int(trade_cmp.bv_f1_rows.sum())} of {int(trade_cmp.bv_rows.sum())} "
          f"({trade_cmp.bv_f1_rows.sum() / max(trade_cmp.bv_rows.sum(), 1):.1%}): the trade log cannot be filtered by market, so F1 is a small slice of each page.")

ok_profile = sum(bv[w]["status"][0] == 200 for w in W)
print(f"\nProfiles returned 200 for {ok_profile} of {n} wallets. Cost: {client.live_used()} Bravado credits, "
      f"{free.live_used()} free requests.")

Sample: the 10 largest F1 wallets by USDC in the recent tape of the 12 largest F1 markets (37% of F1 volume); the tape reaches back to 2026-07-04 at the shallowest market.

Our DB: 0 of 0 F1 trades carry a wallet (0.0%); 0 of the top 10 wallets appear at all.

F1 PnL per token: 11 (wallet, token) pairs; 0 on both sides, 0 Bravado only, 11 free only.
  of the 0 on both sides, 0 agree within $1; max |diff| $nan; wallets whose totals agree within $1: 1 of 10

Trade rows (scan markets): free API holds 251; 61 of them are inside Bravado's page reach, and 0 of those match a Bravado row on (token, second, side, size); 190 are older than Bravado's pages reach.
  Bravado pages cover 4,409 rows over 10 wallets; older pages exist for 4 of them; tx_hash is null on 6% of rows; max price diff on matches nan
  F1 rows Bravado returned in total: 0 of 4409 (0.0%): the trade log cannot be filtered by market, so F1 is a small slice of each page.

Profiles returned 200 for 10 of 10 wallets. Cost: 46 Bravado credits, 0 free requests.

## What this does and doesn't show

**Sample.** Wallets are ranked by USDC traded in the newest rows (at most `TAPE_PAGES` x 500 per market, both sides of each fill) of the `TOP_MARKETS` largest F1 markets. That is "biggest in the recent tape", not all-time, and a market that resolved recently is dominated by its last hours. The coverage table in step 2 shows how far back each market was read. Raise `TAPE_PAGES` or `TOP_MARKETS` to widen it (free requests, cached).

**F1 is matched on `condition_id`.** Most F1 markets in `market_links` hold only their "Yes" token (step 1 counts them), so matching on `token_id` would drop every "No" trade. Bravado's `market_id` is Polymarket's numeric market id (e.g. 525361), not the condition id, so Bravado rows are keyed by `token_id` and mapped to `condition_id` through exact token lookups (`TOKEN_COND`: our `market_links` plus every asset and conditionId pair the free API returned). No names, no regex. Limit: a Bravado "No" token outside the scan markets is not in the map, so F1 totals over all F1 markets understate it.

**Scope of the comparison.** PnL and trade parity use the scan markets only, because the free API filters wallet endpoints by a list of condition ids. Bravado's position list is not filtered by market, so its totals over all F1 markets are in the `f1_pnl_all_f1_markets` column of step 6 and are not compared against anything.

**Trade log depth.** Bravado's trade log cannot be filtered by market and pages from the newest row, so for a busy wallet `TRADE_PAGES` x 500 rows reach back only as far as the `bv_reach` column in step 8. The free API filters on the server and pages back further. Reading a wallet's full F1 history from Bravado costs one credit per 500 rows of that wallet's activity in any market.

**PnL definitions differ.** Bravado reports PnL under its own accounting (PMWAS, net of fees by default; `basis=gross` is documented); Polymarket reports `cashPnl` and `realizedPnl`. Step 7 compares the two per token. Differences are listed, not explained: this notebook does not know which side is right.

**Our DB.** `market_trades` holds taker fills only, and a `wallet` only for rows synced since wallet capture began (step 3 shows the share). This notebook reads the local database, not the VM. Running step 3 against production is a read-only query on the VM and needs the owner's go-ahead.

**Not tested here.** Bravado's `/clob-proxy/holders` (current holders; it returned no rows for a closed NASCAR market in `bravado_data_eval.ipynb`), the leaderboard's `is_mm_bot` flag for these wallets (it exists on leaderboard rows only, and these wallets are not necessarily on a leaderboard page), and the hourly `/pnl` series.

**Privacy.** Outputs contain third-party wallet addresses and pseudonyms. Clear them before committing, and keep `data/cache/` out of git (it is gitignored).